// Generates typed modules from the item bank and copy deck.
//
//   node tools/build-data.mjs
//
// Why a build step rather than importing JSON directly: the app should fail at
// compile time if an item id, scale id or copy id drifts — not at runtime in
// front of someone answering questions about self-harm.

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";

const ROOT = process.cwd();
const OUT = join(ROOT, "src", "data");
mkdirSync(OUT, { recursive: true });

const bank = JSON.parse(readFileSync(join(ROOT, "bank", "v1.json"), "utf8"));
const deck = JSON.parse(readFileSync(join(ROOT, "copy", "deck.en-US.json"), "utf8"));

// ── integrity checks: fail the build, don't warn ───────────────────────────
const errors = [];

const scaleIds = new Set(bank.scales.map(s => s.id));
for (const item of bank.items) {
  if (!scaleIds.has(item.scaleId)) errors.push(`item ${item.id}: unknown scale ${item.scaleId}`);
  if (!bank.responseScales.some(r => r.id === item.responseScaleId))
    errors.push(`item ${item.id}: unknown response scale ${item.responseScaleId}`);
}
for (const scale of bank.scales) {
  for (const role of ["costId", "upsideId"]) {
    const id = scale.report.copy[role];
    if (!deck.entries[id]) errors.push(`scale ${scale.id}: missing copy entry ${id}`);
  }
}
for (const item of bank.items) {
  if (item.safety && !deck.safety[item.safety.resourceSet])
    errors.push(`item ${item.id}: missing safety copy '${item.safety.resourceSet}'`);
}
if (errors.length) {
  for (const e of errors) console.error(`ERROR ${e}`);
  process.exit(1);
}

// ── pagination: six items per screen, safety item last on its page ─────────
const ITEMS_PER_PAGE = 6;

// Interleave scales so a page is never eight items about the same thing —
// that produces obvious response sets and makes the form feel repetitive.
const byScale = new Map();
for (const item of bank.items) {
  if (!byScale.has(item.scaleId)) byScale.set(item.scaleId, []);
  byScale.get(item.scaleId).push(item);
}
const impairmentItems = byScale.get("a9_impairment") ?? [];
const traitItems = [];
{
  const queues = [...byScale.entries()]
    .filter(([id]) => id !== "a9_impairment")
    .map(([, items]) => [...items]);
  let i = 0;
  while (queues.some(q => q.length)) {
    const q = queues[i % queues.length];
    if (q.length) traitItems.push(q.shift());
    i++;
  }
}

// Impairment items go last (they ask about the past two weeks, which is a
// different mental frame), and the risk item is last of all.
const orderedImpairment = [
  ...impairmentItems.filter(i => !i.safety),
  ...impairmentItems.filter(i => i.safety)
];
const ordered = [...traitItems, ...orderedImpairment];

const pages = [];
for (let i = 0; i < ordered.length; i += ITEMS_PER_PAGE) {
  pages.push(ordered.slice(i, i + ITEMS_PER_PAGE).map(item => item.id));
}

// ── emit ───────────────────────────────────────────────────────────────────
const banner = `// GENERATED by tools/build-data.mjs — do not edit.
// Source: bank/v1.json (${bank.version}), copy/deck.en-US.json (${deck.version})
`;

const bankTs = `${banner}
export type ItemId = ${bank.items.map(i => JSON.stringify(i.id)).join(" | ")};
export type ScaleId = ${bank.scales.map(s => JSON.stringify(s.id)).join(" | ")};

export interface ResponseOption { readonly value: number; readonly label: string }
export interface ResponseScale {
  readonly id: string;
  readonly type: string;
  readonly options: readonly ResponseOption[];
  readonly allowNotApplicable: boolean;
  readonly notApplicableLabel?: string;
}
export interface SafetyTrigger {
  readonly atOrAbove: number;
  readonly severity: "support" | "urgent";
  readonly resourceSet: string;
}
export interface Item {
  readonly id: ItemId;
  readonly scaleId: ScaleId;
  readonly facetId?: string;
  readonly text: string;
  readonly responseScaleId: string;
  readonly keyed: "+" | "-";
  readonly timeframe: string;
  readonly safety?: SafetyTrigger;
}
export interface BodyLink {
  readonly system: string;
  readonly grade: "strong" | "moderate" | "preliminary" | "genetic" | "none";
  readonly mechanism: string;
  readonly verification: string | null;
  readonly citations: readonly string[];
}
export interface Scale {
  readonly id: ScaleId;
  readonly name: string;
  readonly poles: { readonly low: string; readonly high: string };
  readonly definition: string;
  readonly minItemsAnswered: number;
  readonly bodyLinks: readonly BodyLink[];
  readonly stateSensitivity: "low" | "medium" | "high";
  readonly internalOnly: boolean;
  readonly costId: string;
  readonly upsideId: string;
}
export interface Citation {
  readonly id: string;
  readonly title: string;
  readonly url: string;
  readonly year?: number;
  readonly claim: string;
}

export const BANK_VERSION = ${JSON.stringify(bank.version)};

export const RESPONSE_SCALES: Readonly<Record<string, ResponseScale>> = ${JSON.stringify(
  Object.fromEntries(bank.responseScales.map(r => [r.id, r])),
  null,
  2
)};

export const SCALES: readonly Scale[] = ${JSON.stringify(
  bank.scales.map(s => ({
    id: s.id,
    name: s.name,
    poles: s.poles,
    definition: s.definition,
    minItemsAnswered: s.scoring.minItemsAnswered,
    bodyLinks: s.bodyLinks,
    stateSensitivity: s.report.stateSensitivity,
    internalOnly: Boolean(s.report.internalOnly),
    costId: s.report.copy.costId,
    upsideId: s.report.copy.upsideId
  })),
  null,
  2
)};

export const ITEMS: readonly Item[] = ${JSON.stringify(
  bank.items.map(i => ({
    id: i.id,
    scaleId: i.scaleId,
    ...(i.facetId ? { facetId: i.facetId } : {}),
    text: i.text,
    responseScaleId: i.responseScaleId,
    keyed: i.keyed,
    timeframe: i.timeframe,
    ...(i.safety
      ? {
          safety: {
            atOrAbove: i.safety.atOrAbove,
            severity: i.safety.severity,
            resourceSet: i.safety.resourceSet
          }
        }
      : {})
  })),
  null,
  2
)};

export const CITATIONS: Readonly<Record<string, Citation>> = ${JSON.stringify(
  Object.fromEntries(bank.citations.map(c => [c.id, c])),
  null,
  2
)};

/** Six per page, scales interleaved, impairment last, risk item last of all. */
export const PAGES: readonly (readonly ItemId[])[] = ${JSON.stringify(pages, null, 2)};

export const ITEMS_BY_ID: Readonly<Record<ItemId, Item>> = Object.fromEntries(
  ITEMS.map(i => [i.id, i])
) as Readonly<Record<ItemId, Item>>;

export const SCALES_BY_ID: Readonly<Record<ScaleId, Scale>> = Object.fromEntries(
  SCALES.map(s => [s.id, s])
) as Readonly<Record<ScaleId, Scale>>;

export const TOTAL_ITEMS = ITEMS.length;
`;

const copyTs = `${banner}
export type CopyId = ${Object.keys(deck.entries).map(k => JSON.stringify(k)).join(" | ")};

export interface CopyEntry { readonly title: string; readonly body: string }
export interface CrisisResource {
  readonly region: string;
  readonly name: string;
  readonly contact: string;
  readonly url: string;
}
export interface SafetyBlock {
  readonly trigger_title?: string;
  readonly trigger_body?: string;
  readonly title?: string;
  readonly body?: string;
  readonly resources?: readonly CrisisResource[];
  readonly continue_label?: string;
  readonly exit_label?: string;
  readonly footer?: string;
}

export const COPY_VERSION = ${JSON.stringify(deck.version)};
export const FRAMING = ${JSON.stringify(deck.framing, null, 2)} as const;
export const BANDS = ${JSON.stringify(deck.bands, null, 2)} as const;
export const ENTRIES: Readonly<Record<CopyId, CopyEntry>> = ${JSON.stringify(deck.entries, null, 2)};
export const SAFETY: Readonly<Record<string, SafetyBlock>> = ${JSON.stringify(deck.safety, null, 2)};
export const BRAVERMAN = ${JSON.stringify(deck.braverman_comparison, null, 2)} as const;
`;

writeFileSync(join(OUT, "bank.ts"), bankTs);
writeFileSync(join(OUT, "copy.ts"), copyTs);

console.log(
  `wrote src/data/bank.ts (${bank.items.length} items, ${bank.scales.length} scales, ` +
    `${pages.length} pages) and src/data/copy.ts (${Object.keys(deck.entries).length} entries)`
);
