// GENERATED by tools/build-data.mjs — do not edit.
// Source: bank/v1.json (0.9.0), copy/deck.en-US.json (0.9.0)

export type ItemId = "a1_drive_e01" | "a1_drive_e02" | "a1_drive_e07" | "a1_drive_e12" | "a1_drive_f02" | "a1_drive_f05" | "a1_drive_f06" | "a1_drive_f10" | "a2_threat_p01" | "a2_threat_p02" | "a2_threat_a02" | "a2_threat_t04" | "a2_threat_t05" | "a2_threat_p05" | "a2_threat_t07" | "a2_threat_a08" | "a3_restraint_c02" | "a3_restraint_f02" | "a3_restraint_b01" | "a3_restraint_c06" | "a3_restraint_f05" | "a3_restraint_b05" | "a3_restraint_c08" | "a3_restraint_f07" | "a4_soc_n01" | "a4_soc_r02" | "a4_soc_d02" | "a4_soc_n06" | "a4_soc_r05" | "a4_soc_d04" | "a4_soc_n07" | "a4_soc_r08" | "a5_ant_c01" | "a5_ant_r02" | "a5_ant_s02" | "a5_ant_r04" | "a5_ant_c04" | "a5_ant_s05" | "a5_ant_r07" | "a5_ant_s08" | "a6_unu_p03" | "a6_unu_a02" | "a6_unu_f02" | "a6_unu_p07" | "a6_unu_a05" | "a6_unu_f05" | "a6_unu_a09" | "a6_unu_f07" | "a7_sys_s01" | "a7_sys_s06" | "a7_sys_l01" | "a7_sys_s05" | "a7_sys_c02" | "a7_sys_l04" | "a7_sys_c07" | "a7_sys_c08" | "a8_epi_01" | "a8_epi_07" | "a8_epi_10" | "a8_epi_12" | "a9_imp_01" | "a9_imp_03" | "a9_imp_05" | "a9_imp_09" | "a9_imp_10";
export type ScaleId = "a1_drive" | "a2_threat" | "a3_restraint" | "a4_sociality" | "a5_antagonism" | "a6_unusual" | "a7_systemizing" | "a8_episodicity" | "a9_impairment";

export interface ResponseOption { readonly value: number; readonly label: string }
export interface ResponseScale {
  readonly id: string;
  readonly type: string;
  readonly options: readonly ResponseOption[];
  readonly allowNotApplicable: boolean;
  readonly notApplicableLabel?: string;
}
export interface SafetyTrigger {
  readonly atOrAbove: number;
  readonly severity: "support" | "urgent";
  readonly resourceSet: string;
}
export interface Item {
  readonly id: ItemId;
  readonly scaleId: ScaleId;
  readonly facetId?: string;
  readonly text: string;
  readonly responseScaleId: string;
  readonly keyed: "+" | "-";
  readonly timeframe: string;
  readonly safety?: SafetyTrigger;
}
export interface BodyLink {
  readonly system: string;
  readonly grade: "strong" | "moderate" | "preliminary" | "genetic" | "none";
  readonly mechanism: string;
  readonly verification: string | null;
  readonly citations: readonly string[];
}
export interface Scale {
  readonly id: ScaleId;
  readonly name: string;
  readonly poles: { readonly low: string; readonly high: string };
  readonly definition: string;
  readonly minItemsAnswered: number;
  readonly bodyLinks: readonly BodyLink[];
  readonly stateSensitivity: "low" | "medium" | "high";
  readonly internalOnly: boolean;
  readonly costId: string;
  readonly upsideId: string;
}
export interface Citation {
  readonly id: string;
  readonly title: string;
  readonly url: string;
  readonly year?: number;
  readonly claim: string;
}

export const BANK_VERSION = "0.9.0";

export const RESPONSE_SCALES: Readonly<Record<string, ResponseScale>> = {
  "agree5": {
    "id": "agree5",
    "type": "likert",
    "allowNotApplicable": false,
    "options": [
      {
        "value": 1,
        "label": "Strongly disagree"
      },
      {
        "value": 2,
        "label": "Disagree"
      },
      {
        "value": 3,
        "label": "Neutral"
      },
      {
        "value": 4,
        "label": "Agree"
      },
      {
        "value": 5,
        "label": "Strongly agree"
      }
    ]
  },
  "impair9": {
    "id": "impair9",
    "type": "impairment",
    "allowNotApplicable": true,
    "notApplicableLabel": "Doesn't apply to my situation",
    "options": [
      {
        "value": 0,
        "label": "Not at all"
      },
      {
        "value": 2,
        "label": "Slightly"
      },
      {
        "value": 4,
        "label": "Definitely"
      },
      {
        "value": 6,
        "label": "Markedly"
      },
      {
        "value": 8,
        "label": "Very severely"
      }
    ]
  }
};

export const SCALES: readonly Scale[] = [
  {
    "id": "a1_drive",
    "name": "Drive",
    "poles": {
      "low": "Inert",
      "high": "Driven"
    },
    "definition": "Tendency to initiate activity and to expend effort for reward, absent external demand.",
    "minItemsAnswered": 5,
    "bodyLinks": [
      {
        "system": "dopamine (reward, effort, exploration)",
        "grade": "strong",
        "mechanism": "Dopamine agonists can produce impulse-control disorders, and amphetamine raises willingness to expend effort for reward.",
        "verification": "Not verifiable at the individual level; the causal evidence comes from drug manipulation, not from measuring a person's level.",
        "citations": [
          "dominion2010",
          "treadway2012",
          "deyoung2013"
        ]
      }
    ],
    "stateSensitivity": "medium",
    "internalOnly": false,
    "costId": "copy_a1_cost",
    "upsideId": "copy_a1_upside"
  },
  {
    "id": "a2_threat",
    "name": "Threat reactivity",
    "poles": {
      "low": "Unflappable",
      "high": "Highly reactive"
    },
    "definition": "How readily and how durably negative emotion is triggered by threat, loss or criticism.",
    "minItemsAnswered": 5,
    "bodyLinks": [
      {
        "system": "serotonin 5-HT2A",
        "grade": "moderate",
        "mechanism": "Cortical 5-HT2A binding tracks the inward facets of neuroticism (r = .37, replicated with a second tracer), and SSRIs lower neuroticism beyond their effect on depression.",
        "verification": "No individual-level test. Group-level PET and drug-response evidence only.",
        "citations": [
          "hogsted2023",
          "tang2009"
        ]
      }
    ],
    "stateSensitivity": "high",
    "internalOnly": false,
    "costId": "copy_a2_cost",
    "upsideId": "copy_a2_upside"
  },
  {
    "id": "a3_restraint",
    "name": "Restraint",
    "poles": {
      "low": "Impulsive",
      "high": "Controlled"
    },
    "definition": "Capacity to hold to an intention against a competing immediate pull.",
    "minItemsAnswered": 5,
    "bodyLinks": [
      {
        "system": "dopamine (reward-cue)",
        "grade": "strong",
        "mechanism": "Dopamine agonists produce impulse-control disorders — gambling, shopping, hypersexuality — in about 17% of Parkinson's patients, reversing on withdrawal.",
        "verification": "Not verifiable at the individual level; the causal evidence is from drug exposure.",
        "citations": [
          "dominion2010"
        ]
      },
      {
        "system": "serotonin (constraint)",
        "grade": "moderate",
        "mechanism": "Serotonin function correlates inversely with aggression and impulsivity (r ≈ -.12 overall, strongest in pharmacological challenge studies), with tryptophan depletion raising aggression in already-prone individuals.",
        "verification": "Group-level challenge studies only.",
        "citations": [
          "duke2013"
        ]
      }
    ],
    "stateSensitivity": "medium",
    "internalOnly": false,
    "costId": "copy_a3_cost",
    "upsideId": "copy_a3_upside"
  },
  {
    "id": "a4_sociality",
    "name": "Sociality",
    "poles": {
      "low": "Detached",
      "high": "Connected"
    },
    "definition": "Baseline need for, and reward from, closeness with other people.",
    "minItemsAnswered": 5,
    "bodyLinks": [
      {
        "system": "μ-opioid",
        "grade": "preliminary",
        "mechanism": "Cerebral μ-opioid receptor availability tracks adult attachment style, with lower availability associated with avoidant attachment.",
        "verification": "PET, and from a single research group. Treat as a lead, not a finding.",
        "citations": [
          "nummenmaa2015"
        ]
      }
    ],
    "stateSensitivity": "high",
    "internalOnly": false,
    "costId": "copy_a4_cost",
    "upsideId": "copy_a4_upside"
  },
  {
    "id": "a5_antagonism",
    "name": "Antagonism",
    "poles": {
      "low": "Accommodating",
      "high": "Combative"
    },
    "definition": "Disposition to pursue one's own interest at others' expense, and to meet friction with force.",
    "minItemsAnswered": 5,
    "bodyLinks": [
      {
        "system": "serotonin",
        "grade": "moderate",
        "mechanism": "Central serotonin function correlates inversely with aggression, anger and hostility (r ≈ -.12 overall, -.21 in pharmacological challenge studies), and tryptophan depletion raises aggression specifically in people already prone to it.",
        "verification": "Group-level challenge studies only.",
        "citations": [
          "duke2013"
        ]
      },
      {
        "system": "androgen exposure (clinical magnitudes only)",
        "grade": "moderate",
        "mechanism": "Congenital adrenal hyperplasia and testosterone therapy shift aggression-related measures, but normal-range testosterone does not — a preregistered trial in 1,000 men found no effect on economic behavior.",
        "verification": "Not applicable to normal variation. Included to state explicitly that the popular 'high testosterone' explanation is unsupported.",
        "citations": [
          "cah_meta2024",
          "geniole2020"
        ]
      }
    ],
    "stateSensitivity": "low",
    "internalOnly": false,
    "costId": "copy_a5_cost",
    "upsideId": "copy_a5_upside"
  },
  {
    "id": "a6_unusual",
    "name": "Unusual cognition",
    "poles": {
      "low": "Conventional",
      "high": "Unusual"
    },
    "definition": "Tendency toward unusual perceptions, associations and beliefs, and to act on them. Scored on form and consequence, never on the content of a belief.",
    "minItemsAnswered": 6,
    "bodyLinks": [
      {
        "system": "dopamine (D2)",
        "grade": "strong",
        "mechanism": "Antipsychotics act by D2 blockade and amphetamine can induce psychosis — the strongest dopamine-to-trait link anywhere in this research, and on a dimension the original Braverman model never mentions.",
        "verification": "No individual-level test; the inference is pharmacological and group-level.",
        "citations": [
          "hitop2021",
          "schizotypy2025"
        ]
      }
    ],
    "stateSensitivity": "medium",
    "internalOnly": true,
    "costId": "copy_a6_cost",
    "upsideId": "copy_a6_upside"
  },
  {
    "id": "a7_systemizing",
    "name": "Systemizing",
    "poles": {
      "low": "Fluid / social",
      "high": "Systematic / literal"
    },
    "definition": "Preference for deriving rules and structure over reading people and context, together with heightened sensitivity to detail and change.",
    "minItemsAnswered": 5,
    "bodyLinks": [
      {
        "system": "polygenic — no transmitter account",
        "grade": "genetic",
        "mechanism": "Autistic traits are continuously distributed in the general population and highly heritable, but no clean neurotransmitter story exists. Saying so is part of the point.",
        "verification": "Formal assessment for the clinical end; the trait itself is not confirmable by any biomarker.",
        "citations": [
          "aq_dimensional2022",
          "aq_factor2019"
        ]
      }
    ],
    "stateSensitivity": "low",
    "internalOnly": false,
    "costId": "copy_a7_cost",
    "upsideId": "copy_a7_upside"
  },
  {
    "id": "a8_episodicity",
    "name": "Episodicity",
    "poles": {
      "low": "Steady",
      "high": "Cycling"
    },
    "definition": "Degree to which energy, confidence and output arrive in distinct phases rather than at a steady level.",
    "minItemsAnswered": 3,
    "bodyLinks": [
      {
        "system": "none claimed",
        "grade": "none",
        "mechanism": "No direct transmitter claim. The scale is justified predictively: the Hypomanic Personality Scale was the single best predictor of later bipolar disorder in a 23-year birth-cohort follow-up (d = 0.67).",
        "verification": "Clinical assessment at the high end; prospective mood charting.",
        "citations": [
          "hps_finland2022"
        ]
      }
    ],
    "stateSensitivity": "medium",
    "internalOnly": true,
    "costId": "copy_a8_cost",
    "upsideId": "copy_a8_upside"
  },
  {
    "id": "a9_impairment",
    "name": "Impairment",
    "poles": {
      "low": "Unaffected",
      "high": "Severely affected"
    },
    "definition": "How much current functioning is affected, whatever the cause. Crossed with every other scale to separate a feature of how someone is built from something that is costing them.",
    "minItemsAnswered": 4,
    "bodyLinks": [
      {
        "system": "none",
        "grade": "none",
        "mechanism": "Functional impact is measured directly and carries no biological claim. This scale deliberately does not ask why.",
        "verification": null,
        "citations": []
      }
    ],
    "stateSensitivity": "high",
    "internalOnly": false,
    "costId": "copy_a9_cost",
    "upsideId": "copy_a9_upside"
  }
];

export const ITEMS: readonly Item[] = [
  {
    "id": "a1_drive_e01",
    "scaleId": "a1_drive",
    "facetId": "a1_drive.exploration",
    "text": "I start things nobody asked me to start.",
    "responseScaleId": "agree5",
    "keyed": "+",
    "timeframe": "general"
  },
  {
    "id": "a1_drive_e02",
    "scaleId": "a1_drive",
    "facetId": "a1_drive.exploration",
    "text": "I'd rather stick with what already works than try an unfamiliar option.",
    "responseScaleId": "agree5",
    "keyed": "-",
    "timeframe": "general"
  },
  {
    "id": "a1_drive_e07",
    "scaleId": "a1_drive",
    "facetId": "a1_drive.exploration",
    "text": "Once I finish something, I'm happy to let the next thing wait.",
    "responseScaleId": "agree5",
    "keyed": "-",
    "timeframe": "general"
  },
  {
    "id": "a1_drive_e12",
    "scaleId": "a1_drive",
    "facetId": "a1_drive.exploration",
    "text": "People close to me have asked me to stop starting things.",
    "responseScaleId": "agree5",
    "keyed": "+",
    "timeframe": "general"
  },
  {
    "id": "a1_drive_f02",
    "scaleId": "a1_drive",
    "facetId": "a1_drive.effort",
    "text": "I often decide the effort outweighs the payoff.",
    "responseScaleId": "agree5",
    "keyed": "-",
    "timeframe": "general"
  },
  {
    "id": "a1_drive_f05",
    "scaleId": "a1_drive",
    "facetId": "a1_drive.effort",
    "text": "I keep working on a problem after other people have set it aside.",
    "responseScaleId": "agree5",
    "keyed": "+",
    "timeframe": "general"
  },
  {
    "id": "a1_drive_f06",
    "scaleId": "a1_drive",
    "facetId": "a1_drive.effort",
    "text": "I lose interest once the interesting part of a project is over.",
    "responseScaleId": "agree5",
    "keyed": "-",
    "timeframe": "general"
  },
  {
    "id": "a1_drive_f10",
    "scaleId": "a1_drive",
    "facetId": "a1_drive.effort",
    "text": "I've pushed myself to exhaustion for something nobody required of me.",
    "responseScaleId": "agree5",
    "keyed": "+",
    "timeframe": "general"
  },
  {
    "id": "a2_threat_p01",
    "scaleId": "a2_threat",
    "facetId": "a2_threat.persistence",
    "text": "Something that went wrong hours ago is still running in my head.",
    "responseScaleId": "agree5",
    "keyed": "+",
    "timeframe": "general"
  },
  {
    "id": "a2_threat_p02",
    "scaleId": "a2_threat",
    "facetId": "a2_threat.persistence",
    "text": "Once a difficult conversation ends, I stop thinking about it.",
    "responseScaleId": "agree5",
    "keyed": "-",
    "timeframe": "general"
  },
  {
    "id": "a2_threat_a02",
    "scaleId": "a2_threat",
    "facetId": "a2_threat.anticipation",
    "text": "My mind stays on what's in front of me rather than what might go wrong.",
    "responseScaleId": "agree5",
    "keyed": "-",
    "timeframe": "general"
  },
  {
    "id": "a2_threat_t04",
    "scaleId": "a2_threat",
    "facetId": "a2_threat.trigger",
    "text": "People describe me as hard to upset.",
    "responseScaleId": "agree5",
    "keyed": "-",
    "timeframe": "general"
  },
  {
    "id": "a2_threat_t05",
    "scaleId": "a2_threat",
    "facetId": "a2_threat.trigger",
    "text": "A short, neutral message from someone can put me on edge.",
    "responseScaleId": "agree5",
    "keyed": "+",
    "timeframe": "general"
  },
  {
    "id": "a2_threat_p05",
    "scaleId": "a2_threat",
    "facetId": "a2_threat.persistence",
    "text": "A single piece of criticism can stay with me for days.",
    "responseScaleId": "agree5",
    "keyed": "+",
    "timeframe": "general"
  },
  {
    "id": "a2_threat_t07",
    "scaleId": "a2_threat",
    "facetId": "a2_threat.trigger",
    "text": "The smallest sign of disapproval can change how my whole day feels.",
    "responseScaleId": "agree5",
    "keyed": "+",
    "timeframe": "general"
  },
  {
    "id": "a2_threat_a08",
    "scaleId": "a2_threat",
    "facetId": "a2_threat.anticipation",
    "text": "I can walk into a situation with an uncertain outcome feeling no dread at all.",
    "responseScaleId": "agree5",
    "keyed": "-",
    "timeframe": "general"
  },
  {
    "id": "a3_restraint_c02",
    "scaleId": "a3_restraint",
    "facetId": "a3_restraint.cue",
    "text": "I can have something tempting in the house and forget it's there.",
    "responseScaleId": "agree5",
    "keyed": "+",
    "timeframe": "general"
  },
  {
    "id": "a3_restraint_f02",
    "scaleId": "a3_restraint",
    "facetId": "a3_restraint.followthrough",
    "text": "I move to whatever's more appealing before the current thing is done.",
    "responseScaleId": "agree5",
    "keyed": "-",
    "timeframe": "general"
  },
  {
    "id": "a3_restraint_b01",
    "scaleId": "a3_restraint",
    "facetId": "a3_restraint.brake",
    "text": "I've said something in the moment that cost me later.",
    "responseScaleId": "agree5",
    "keyed": "-",
    "timeframe": "general"
  },
  {
    "id": "a3_restraint_c06",
    "scaleId": "a3_restraint",
    "facetId": "a3_restraint.cue",
    "text": "When something I've given up is right in front of me, it stays easy to ignore.",
    "responseScaleId": "agree5",
    "keyed": "+",
    "timeframe": "general"
  },
  {
    "id": "a3_restraint_f05",
    "scaleId": "a3_restraint",
    "facetId": "a3_restraint.followthrough",
    "text": "Once I commit to a plan, I stay with it even when a better offer appears.",
    "responseScaleId": "agree5",
    "keyed": "+",
    "timeframe": "general"
  },
  {
    "id": "a3_restraint_b05",
    "scaleId": "a3_restraint",
    "facetId": "a3_restraint.brake",
    "text": "I send messages I later wish I'd slept on.",
    "responseScaleId": "agree5",
    "keyed": "-",
    "timeframe": "general"
  },
  {
    "id": "a3_restraint_c08",
    "scaleId": "a3_restraint",
    "facetId": "a3_restraint.cue",
    "text": "I gave something up years ago and have stuck with it, even when the pull came back.",
    "responseScaleId": "agree5",
    "keyed": "+",
    "timeframe": "lifetime"
  },
  {
    "id": "a3_restraint_f07",
    "scaleId": "a3_restraint",
    "facetId": "a3_restraint.followthrough",
    "text": "People have stopped relying on me to finish what I take on.",
    "responseScaleId": "agree5",
    "keyed": "-",
    "timeframe": "general"
  },
  {
    "id": "a4_soc_n01",
    "scaleId": "a4_sociality",
    "facetId": "a4_sociality.need",
    "text": "I notice the gap when it's been a while since I saw anyone close to me.",
    "responseScaleId": "agree5",
    "keyed": "+",
    "timeframe": "general"
  },
  {
    "id": "a4_soc_r02",
    "scaleId": "a4_sociality",
    "facetId": "a4_sociality.reward",
    "text": "Time with people leaves my mood about where it started.",
    "responseScaleId": "agree5",
    "keyed": "-",
    "timeframe": "general"
  },
  {
    "id": "a4_soc_d02",
    "scaleId": "a4_sociality",
    "facetId": "a4_sociality.disclosure",
    "text": "I keep parts of my life separate from everyone.",
    "responseScaleId": "agree5",
    "keyed": "-",
    "timeframe": "general"
  },
  {
    "id": "a4_soc_n06",
    "scaleId": "a4_sociality",
    "facetId": "a4_sociality.need",
    "text": "Most times, I'd choose a weekend alone over a weekend with people.",
    "responseScaleId": "agree5",
    "keyed": "-",
    "timeframe": "general"
  },
  {
    "id": "a4_soc_r05",
    "scaleId": "a4_sociality",
    "facetId": "a4_sociality.reward",
    "text": "I look forward to seeing certain people the way other people look forward to a holiday.",
    "responseScaleId": "agree5",
    "keyed": "+",
    "timeframe": "general"
  },
  {
    "id": "a4_soc_d04",
    "scaleId": "a4_sociality",
    "facetId": "a4_sociality.disclosure",
    "text": "The people close to me get the honest version of how I'm doing.",
    "responseScaleId": "agree5",
    "keyed": "+",
    "timeframe": "general"
  },
  {
    "id": "a4_soc_n07",
    "scaleId": "a4_sociality",
    "facetId": "a4_sociality.need",
    "text": "A long stretch apart from people I'm close to starts to feel physically unsettling.",
    "responseScaleId": "agree5",
    "keyed": "+",
    "timeframe": "general"
  },
  {
    "id": "a4_soc_r08",
    "scaleId": "a4_sociality",
    "facetId": "a4_sociality.reward",
    "text": "What people get out of closeness has always been a mystery to me.",
    "responseScaleId": "agree5",
    "keyed": "-",
    "timeframe": "lifetime"
  },
  {
    "id": "a5_ant_c01",
    "scaleId": "a5_antagonism",
    "facetId": "a5_antagonism.callousness",
    "text": "How my decisions land on other people is mostly an afterthought.",
    "responseScaleId": "agree5",
    "keyed": "+",
    "timeframe": "general"
  },
  {
    "id": "a5_ant_r02",
    "scaleId": "a5_antagonism",
    "facetId": "a5_antagonism.retaliation",
    "text": "When someone's rude to me, I let it go.",
    "responseScaleId": "agree5",
    "keyed": "-",
    "timeframe": "general"
  },
  {
    "id": "a5_ant_s02",
    "scaleId": "a5_antagonism",
    "facetId": "a5_antagonism.suspicion",
    "text": "I give people the benefit of the doubt by default.",
    "responseScaleId": "agree5",
    "keyed": "-",
    "timeframe": "general"
  },
  {
    "id": "a5_ant_r04",
    "scaleId": "a5_antagonism",
    "facetId": "a5_antagonism.retaliation",
    "text": "I keep an argument going until the other person backs down.",
    "responseScaleId": "agree5",
    "keyed": "+",
    "timeframe": "general"
  },
  {
    "id": "a5_ant_c04",
    "scaleId": "a5_antagonism",
    "facetId": "a5_antagonism.callousness",
    "text": "Seeing someone upset affects me.",
    "responseScaleId": "agree5",
    "keyed": "-",
    "timeframe": "general"
  },
  {
    "id": "a5_ant_s05",
    "scaleId": "a5_antagonism",
    "facetId": "a5_antagonism.suspicion",
    "text": "I've been proved right about people I was wary of.",
    "responseScaleId": "agree5",
    "keyed": "+",
    "timeframe": "lifetime"
  },
  {
    "id": "a5_ant_r07",
    "scaleId": "a5_antagonism",
    "facetId": "a5_antagonism.retaliation",
    "text": "I've gone out of my way to get back at someone.",
    "responseScaleId": "agree5",
    "keyed": "+",
    "timeframe": "lifetime"
  },
  {
    "id": "a5_ant_s08",
    "scaleId": "a5_antagonism",
    "facetId": "a5_antagonism.suspicion",
    "text": "It wouldn't occur to me that someone close to me might be using me.",
    "responseScaleId": "agree5",
    "keyed": "-",
    "timeframe": "general"
  },
  {
    "id": "a6_unu_p03",
    "scaleId": "a6_unusual",
    "facetId": "a6_unusual.perceptual",
    "text": "Movement at the edge of my vision sometimes turns out to be imaginary.",
    "responseScaleId": "agree5",
    "keyed": "+",
    "timeframe": "general"
  },
  {
    "id": "a6_unu_a02",
    "scaleId": "a6_unusual",
    "facetId": "a6_unusual.associative",
    "text": "My thinking is conventional and I'm fine with that.",
    "responseScaleId": "agree5",
    "keyed": "-",
    "timeframe": "general"
  },
  {
    "id": "a6_unu_f02",
    "scaleId": "a6_unusual",
    "facetId": "a6_unusual.referential",
    "text": "I take what happens around me as coincidence.",
    "responseScaleId": "agree5",
    "keyed": "-",
    "timeframe": "general"
  },
  {
    "id": "a6_unu_p07",
    "scaleId": "a6_unusual",
    "facetId": "a6_unusual.perceptual",
    "text": "As far as I can tell, I perceive the world the same way everyone else does.",
    "responseScaleId": "agree5",
    "keyed": "-",
    "timeframe": "general"
  },
  {
    "id": "a6_unu_a05",
    "scaleId": "a6_unusual",
    "facetId": "a6_unusual.associative",
    "text": "I've worked out how things fit together in a way others couldn't follow.",
    "responseScaleId": "agree5",
    "keyed": "+",
    "timeframe": "general"
  },
  {
    "id": "a6_unu_f05",
    "scaleId": "a6_unusual",
    "facetId": "a6_unusual.referential",
    "text": "A stranger's passing comment has felt like it was aimed at me.",
    "responseScaleId": "agree5",
    "keyed": "+",
    "timeframe": "general"
  },
  {
    "id": "a6_unu_a09",
    "scaleId": "a6_unusual",
    "facetId": "a6_unusual.associative",
    "text": "Even my most unusual ideas turn out to be ones plenty of other people share.",
    "responseScaleId": "agree5",
    "keyed": "-",
    "timeframe": "general"
  },
  {
    "id": "a6_unu_f07",
    "scaleId": "a6_unusual",
    "facetId": "a6_unusual.referential",
    "text": "I've changed my plans because events seemed to be pointing at me.",
    "responseScaleId": "agree5",
    "keyed": "+",
    "timeframe": "lifetime"
  },
  {
    "id": "a7_sys_s01",
    "scaleId": "a7_systemizing",
    "facetId": "a7_systemizing.rule",
    "text": "I need to know how something works before I'm comfortable using it.",
    "responseScaleId": "agree5",
    "keyed": "+",
    "timeframe": "general"
  },
  {
    "id": "a7_sys_s06",
    "scaleId": "a7_systemizing",
    "facetId": "a7_systemizing.rule",
    "text": "I prefer to feel my way through a new situation rather than map it out.",
    "responseScaleId": "agree5",
    "keyed": "-",
    "timeframe": "general"
  },
  {
    "id": "a7_sys_l01",
    "scaleId": "a7_systemizing",
    "facetId": "a7_systemizing.literality",
    "text": "I read between the lines easily in conversation.",
    "responseScaleId": "agree5",
    "keyed": "-",
    "timeframe": "general"
  },
  {
    "id": "a7_sys_s05",
    "scaleId": "a7_systemizing",
    "facetId": "a7_systemizing.rule",
    "text": "I'd rather have an explicit procedure than be told to use my judgement.",
    "responseScaleId": "agree5",
    "keyed": "+",
    "timeframe": "general"
  },
  {
    "id": "a7_sys_c02",
    "scaleId": "a7_systemizing",
    "facetId": "a7_systemizing.detail",
    "text": "Small changes to a room usually pass me by.",
    "responseScaleId": "agree5",
    "keyed": "-",
    "timeframe": "general"
  },
  {
    "id": "a7_sys_l04",
    "scaleId": "a7_systemizing",
    "facetId": "a7_systemizing.literality",
    "text": "People have told me I take things too literally.",
    "responseScaleId": "agree5",
    "keyed": "+",
    "timeframe": "general"
  },
  {
    "id": "a7_sys_c07",
    "scaleId": "a7_systemizing",
    "facetId": "a7_systemizing.detail",
    "text": "I've had to leave somewhere because the noise, light or crowding became unbearable.",
    "responseScaleId": "agree5",
    "keyed": "+",
    "timeframe": "lifetime"
  },
  {
    "id": "a7_sys_c08",
    "scaleId": "a7_systemizing",
    "facetId": "a7_systemizing.detail",
    "text": "I can move between very different environments all day and feel much the same.",
    "responseScaleId": "agree5",
    "keyed": "-",
    "timeframe": "general"
  },
  {
    "id": "a8_epi_01",
    "scaleId": "a8_episodicity",
    "text": "My energy and confidence come in waves rather than staying level.",
    "responseScaleId": "agree5",
    "keyed": "+",
    "timeframe": "general"
  },
  {
    "id": "a8_epi_07",
    "scaleId": "a8_episodicity",
    "text": "My sense of what I'm capable of has stayed steady my whole life.",
    "responseScaleId": "agree5",
    "keyed": "-",
    "timeframe": "lifetime"
  },
  {
    "id": "a8_epi_10",
    "scaleId": "a8_episodicity",
    "text": "In my most energetic phases I've made decisions I later couldn't explain.",
    "responseScaleId": "agree5",
    "keyed": "+",
    "timeframe": "lifetime"
  },
  {
    "id": "a8_epi_12",
    "scaleId": "a8_episodicity",
    "text": "Even at my busiest, I feel like the same person I always am.",
    "responseScaleId": "agree5",
    "keyed": "-",
    "timeframe": "lifetime"
  },
  {
    "id": "a9_imp_01",
    "scaleId": "a9_impairment",
    "text": "Because of how I've been feeling or functioning, my work or studies have suffered.",
    "responseScaleId": "impair9",
    "keyed": "+",
    "timeframe": "past-2-weeks"
  },
  {
    "id": "a9_imp_03",
    "scaleId": "a9_impairment",
    "text": "Because of how I've been feeling or functioning, I've done less of what I enjoy.",
    "responseScaleId": "impair9",
    "keyed": "+",
    "timeframe": "past-2-weeks"
  },
  {
    "id": "a9_imp_05",
    "scaleId": "a9_impairment",
    "text": "In the past two weeks I've avoided things I'd normally do.",
    "responseScaleId": "impair9",
    "keyed": "+",
    "timeframe": "past-2-weeks"
  },
  {
    "id": "a9_imp_09",
    "scaleId": "a9_impairment",
    "text": "In the past two weeks, basic daily demands have been beyond me.",
    "responseScaleId": "impair9",
    "keyed": "+",
    "timeframe": "past-2-weeks"
  },
  {
    "id": "a9_imp_10",
    "scaleId": "a9_impairment",
    "text": "In the past two weeks I've had thoughts of hurting myself.",
    "responseScaleId": "impair9",
    "keyed": "+",
    "timeframe": "past-2-weeks",
    "safety": {
      "atOrAbove": 2,
      "severity": "urgent",
      "resourceSet": "crisis.suicide"
    }
  }
];

export const CITATIONS: Readonly<Record<string, Citation>> = {
  "aq_dimensional2022": {
    "id": "aq_dimensional2022",
    "title": "Autism traits dimensionality and multivariate relationship with alexithymia and anxiety in the general population",
    "url": "https://www.sciencedirect.com/science/article/pii/S0891422222001913",
    "year": 2022,
    "claim": "Autistic traits are continuously distributed through the general population rather than forming a discrete category."
  },
  "aq_factor2019": {
    "id": "aq_factor2019",
    "title": "A comprehensive psychometric analysis of autism-spectrum quotient factor models using two large samples",
    "url": "https://pubmed.ncbi.nlm.nih.gov/31464106/",
    "year": 2019,
    "claim": "The AQ's factor structure is unstable across samples; a reduced multi-factor solution performs best in both community and clinical data."
  },
  "cah_meta2024": {
    "id": "cah_meta2024",
    "title": "Prenatal androgen exposure and sex-typical play behaviour: a meta-analysis of classic congenital adrenal hyperplasia studies",
    "url": "https://pubmed.ncbi.nlm.nih.gov/38447820/",
    "year": 2024,
    "claim": "Clinical-magnitude prenatal androgen exposure shifts behavior, including physical aggression and tender-mindedness."
  },
  "deyoung2013": {
    "id": "deyoung2013",
    "title": "The neuromodulator of exploration: a unifying theory of the role of dopamine in personality",
    "url": "https://www.frontiersin.org/journals/human-neuroscience/articles/10.3389/fnhum.2013.00762/full",
    "year": 2013,
    "claim": "Dopamine's general function is to promote exploration, linking it to Extraversion and Openness/Intellect."
  },
  "dominion2010": {
    "id": "dominion2010",
    "title": "DOMINION study: impulse control disorders in Parkinson's disease",
    "url": "https://www.medscape.com/viewarticle/721768",
    "year": 2010,
    "claim": "Impulse control disorders occur in about 17% of Parkinson's patients taking a dopamine agonist, 2-3x the rate of those not taking one."
  },
  "duke2013": {
    "id": "duke2013",
    "title": "Revisiting the serotonin-aggression relation in humans: a meta-analysis",
    "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC3718863/",
    "year": 2013,
    "claim": "Central serotonin function correlates inversely with aggression, anger and hostility (r = -.12; -.21 in pharmacological challenge)."
  },
  "geniole2020": {
    "id": "geniole2020",
    "title": "Is testosterone linked to human aggression? A meta-analytic examination of baseline, dynamic and manipulated testosterone",
    "url": "https://www.researchgate.net/publication/337658220",
    "year": 2020,
    "claim": "Baseline testosterone correlates with aggression at only r ≈ .07, with no evidence of a causal effect from administration."
  },
  "hitop2021": {
    "id": "hitop2021",
    "title": "The Hierarchical Taxonomy of Psychopathology (HiTOP): a quantitative nosology based on consensus of evidence",
    "url": "https://pubmed.ncbi.nlm.nih.gov/33577350/",
    "year": 2021,
    "claim": "Psychopathology including the thought-disorder spectrum is distributed dimensionally rather than categorically."
  },
  "hogsted2023": {
    "id": "hogsted2023",
    "title": "The association between brain serotonin 2A receptor binding and neuroticism in healthy individuals: a Cimbi database independent replication study",
    "url": "https://www.biorxiv.org/content/10.1101/2023.08.24.554575",
    "year": 2023,
    "claim": "Cortical 5-HT2A binding is associated with the inward facets of neuroticism (r = .37) in an independent replication."
  },
  "hps_finland2022": {
    "id": "hps_finland2022",
    "title": "Predictive and discriminant validity of psychopathology and temperament scales — 23-year follow-up, Northern Finland Birth Cohort 1966",
    "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC9564146/",
    "year": 2022,
    "claim": "High Hypomanic Personality Scale score was the best single predictor of later bipolar disorder (d = 0.67)."
  },
  "nummenmaa2015": {
    "id": "nummenmaa2015",
    "title": "Adult attachment style is associated with cerebral μ-opioid receptor availability in humans",
    "url": "https://pubmed.ncbi.nlm.nih.gov/26046928/",
    "year": 2015,
    "claim": "μ-opioid receptor availability tracks adult attachment style; lower availability is associated with avoidant attachment."
  },
  "schizotypy2025": {
    "id": "schizotypy2025",
    "title": "Predictive validity of psychometrically assessed schizotypy for psychopathology dimensions and functioning in an 8-year multiwave study",
    "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC11879525/",
    "year": 2025,
    "claim": "Positive and negative schizotypy measured in non-clinical samples predict later symptoms and functioning along distinct paths."
  },
  "tang2009": {
    "id": "tang2009",
    "title": "Personality change during depression treatment: a placebo-controlled trial",
    "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC2799251",
    "year": 2009,
    "claim": "Paroxetine reduced neuroticism 6.8x as much as placebo among patients matched for depression improvement."
  },
  "treadway2012": {
    "id": "treadway2012",
    "title": "Dopaminergic mechanisms of individual differences in human effort-based decision-making",
    "url": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3391699/",
    "year": 2012,
    "claim": "Striatal and vmPFC dopamine responsivity predicts willingness to expend effort for larger rewards."
  }
};

/** Six per page, scales interleaved, impairment last, risk item last of all. */
export const PAGES: readonly (readonly ItemId[])[] = [
  [
    "a1_drive_e01",
    "a2_threat_p01",
    "a3_restraint_c02",
    "a4_soc_n01",
    "a5_ant_c01",
    "a6_unu_p03"
  ],
  [
    "a7_sys_s01",
    "a8_epi_01",
    "a1_drive_e02",
    "a2_threat_p02",
    "a3_restraint_f02",
    "a4_soc_r02"
  ],
  [
    "a5_ant_r02",
    "a6_unu_a02",
    "a7_sys_s06",
    "a8_epi_07",
    "a1_drive_e07",
    "a2_threat_a02"
  ],
  [
    "a3_restraint_b01",
    "a4_soc_d02",
    "a5_ant_s02",
    "a6_unu_f02",
    "a7_sys_l01",
    "a8_epi_10"
  ],
  [
    "a1_drive_e12",
    "a2_threat_t04",
    "a3_restraint_c06",
    "a4_soc_n06",
    "a5_ant_r04",
    "a6_unu_p07"
  ],
  [
    "a7_sys_s05",
    "a8_epi_12",
    "a1_drive_f02",
    "a2_threat_t05",
    "a3_restraint_f05",
    "a4_soc_r05"
  ],
  [
    "a5_ant_c04",
    "a6_unu_a05",
    "a7_sys_c02",
    "a1_drive_f05",
    "a2_threat_p05",
    "a3_restraint_b05"
  ],
  [
    "a4_soc_d04",
    "a5_ant_s05",
    "a6_unu_f05",
    "a7_sys_l04",
    "a1_drive_f06",
    "a2_threat_t07"
  ],
  [
    "a3_restraint_c08",
    "a4_soc_n07",
    "a5_ant_r07",
    "a6_unu_a09",
    "a7_sys_c07",
    "a1_drive_f10"
  ],
  [
    "a2_threat_a08",
    "a3_restraint_f07",
    "a4_soc_r08",
    "a5_ant_s08",
    "a6_unu_f07",
    "a7_sys_c08"
  ],
  [
    "a9_imp_01",
    "a9_imp_03",
    "a9_imp_05",
    "a9_imp_09",
    "a9_imp_10"
  ]
];

export const ITEMS_BY_ID: Readonly<Record<ItemId, Item>> = Object.fromEntries(
  ITEMS.map(i => [i.id, i])
) as Readonly<Record<ItemId, Item>>;

export const SCALES_BY_ID: Readonly<Record<ScaleId, Scale>> = Object.fromEntries(
  SCALES.map(s => [s.id, s])
) as Readonly<Record<ScaleId, Scale>>;

export const TOTAL_ITEMS = ITEMS.length;
